Create composite pre commit action
ccao-data/actions pull request #22
Opened 2024-04-16 15:47 UTC by wagnerlmichael

Test

2024-04-16 16:18 UTC, wagnerlmichael commented on pre-commit/action.yaml
> +        done
This bash script takes the input string from sales val repo, iterates through it to convert it to an array, and then runs the pre commit for each of the hooks

2024-04-16 19:28 UTC, wagnerlmichael commented on pre-commit/action.yaml
> +      shell: bash
Bash script that parses string input from sales val (or any other external repo) into an array of strings which is then iterated through with a for loop.

2024-04-16 21:46 UTC, jeancochrane requested changes
Looking great! One blocking suggestion: How about we refactor the [`pre-commit` workflow in this repo](https://github.com/ccao-data/actions/blob/main/.github/workflows/pre-commit.yaml) to use this new action as well? That way we can always be sure that any changes we make to this action don't introduce any obvious bugs (although there's always the possibility of introducing breaking changes that affect repos that call this action).

2024-04-16 21:46 UTC, jeancochrane commented on pre-commit/action.yaml
> +    default: ''
**[Thought, non-blocking]** I wonder if a more sensible default would be to run _all_ of the hooks defined in the config, rather than none of them? That's a speculative thought, however, and I think this way could work too -- it just might surprise a dev who sets it up, forgets to specify the hooks, sees it pass, and assumes that all of the hooks passed rather than that none of them ran at all!

2024-04-16 21:46 UTC, jeancochrane commented on pre-commit/action.yaml
> +      uses: actions/checkout@v2
**[Nitpick, non-blocking]** `actions/checkout` is actually on `v4` already!

```suggestion
      uses: actions/checkout@v4
```

2024-04-16 21:46 UTC, jeancochrane commented on pre-commit/action.yaml
> +    - name: Run pre-commit
**[Nitpick, non-blocking]** Missing a newline here:

```suggestion
          }}

    - name: Run pre-commit
```

2024-04-16 21:49 UTC, jeancochrane commented on pre-commit/action.yaml
> +      uses: actions/cache@v2
**[Nitpick, non-blocking]** `actions/cache` is also on `v4`:

```suggestion
      uses: actions/cache@v4
```

2024-04-17 19:17 UTC, dfsnow requested changes
I should've been more explicit in my issue definition/ask here. The purpose of the issue here is just to codify our [existing pre-commit](https://github.com/ccao-data/data-architecture/blob/master/.github/workflows/pre-commit.yaml#L9) workflow as a composite action, since the code is used across all repos.

We _don't_ really need a way to define the hooks across repos. I'd much prefer to leave that to the local `.pre-commit-config.yaml`.

The three issues we're trying to solve with the composite action are:

1. Standardizing our own pre-commit action rather than the [deprecated official one](https://github.com/pre-commit/action/blob/main/action.yml)
2. Reducing code duplication across repos
3. Updating and debugging the [caching logic](https://github.com/ccao-data/data-architecture/blob/408573e17ee893b6afc9df509c34a7861be0e5cc/.github/workflows/pre-commit.yaml#L32) to support our common hooks. The R caching works most of the time but has intermittent, seemingly random failures (that are resolved by re-running the workflow).

Apologies, I should have clarified this issue more.

2024-04-17 19:17 UTC, dfsnow commented on pre-commit/action.yaml
> +      shell: bash
**praise:** Nice thinking @jeancochrane

2024-04-18 21:55 UTC, jeancochrane approved these changes
Looks great!

2024-04-18 21:55 UTC, jeancochrane commented on .github/workflows/pre-commit.yaml
> +        uses: ccao-data/actions/pre-commit@create-composite-pre-commit-action
**[Suggestion, non-blocking]** Nice! Note that there will be a bit of a catch-22 when merging this -- the new action won't be on the `main` branch until we merge the PR, so CI checks will fail if you try to adjust the version before merging, but _after_ you merge the branch will be deleted, so checks will also fail. There are two ways to get around this:

1. Remove the branch reference before merging, and let someone with admin permissions on this repo (me or Dan) force-merge the PR despite the failing check
2. Keep the branch reference while merging, and put up a super simple PR immediately after merging to remove the reference

I'm fine with either, just let me know what your plan is and we'll go from there!

2024-04-19 18:45 UTC, dfsnow approved these changes
This looks set to me. I'm down for the plan of merging this, updating the repos, and looking for caching issues during that process.

2024-04-22 17:54 UTC, merged